### ISSUE TITLE
Compilation issue on arm(aarch64)

### ISSUE THREAD

**Issue by dpratiher** [fakenmc/cf4ocl#36]
In file included from /home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/Frontend/ASTUnit.h:18:0,
                 from /home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/Frontend/FrontendAction.h:24,
                 from /home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/CodeGen/CodeGenAction.h:13,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:47:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/AST/ASTContext.h: In member function ‘const clang::ast_type_traits::DynTypedNode* clang::ASTContext::DynTypedNodeList::begin() const’:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/AST/ASTContext.h:558:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             ->begin();
             ^
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/AST/ASTContext.h: In member function ‘const clang::ast_type_traits::DynTypedNode* clang::ASTContext::DynTypedNodeList::end() const’:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/include/clang/AST/ASTContext.h:565:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             ->end();
             ^
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp: At global scope:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:108:6: error: prototype for ‘bool amd::opencl_driver::File::WriteData(const char*, size_t)’ does not match any in class ‘amd::opencl_driver::File’
 bool File::WriteData(const char* ptr, size_t size)
      ^
In file included from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:0:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:85:8: error: candidate is: bool amd::opencl_driver::File::WriteData(const char*, int)
   bool WriteData(const char* ptr, size_t size);
        ^
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp: In member function ‘virtual amd::opencl_driver::FileReference* amd::opencl_driver::BufferReference::ToInputFile(amd::opencl_driver::Compiler*, amd::opencl_driver::File*)’:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:170:26: error: ‘size’ was not declared in this scope
   if (!f->WriteData(ptr, size)) { return 0; }
                          ^
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp: At global scope:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:315:20: error: ‘amd::opencl_driver::BufferReference* amd::opencl_driver::AMDGPUCompiler::NewBufferReference(amd::opencl_driver::DataType, const char*, size_t, const string&)’ marked ‘override’, but does not override
   BufferReference* NewBufferReference(DataType type, const char* ptr, size_t size, const std::string& id) override;
                    ^
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp: In member function ‘virtual bool amd::opencl_driver::AMDGPUCompiler::DumpExecutableAsText(amd::opencl_driver::Buffer*, amd::opencl_driver::File*)’:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:710:40: error: ‘class amd::opencl_driver::Buffer’ has no member named ‘Size’
   StringRef execRef(exec->Ptr(), exec->Size());
                                        ^
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp: In member function ‘amd::opencl_driver::Compiler* amd::opencl_driver::CompilerFactory::CreateAMDGPUCompiler(const string&)’:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:761:36: error: invalid new-expression of abstract class type ‘amd::opencl_driver::AMDGPUCompiler’
   return new AMDGPUCompiler(llvmBin);
                                    ^
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:266:7: note:   because the following virtual functions are pure within ‘amd::opencl_driver::AMDGPUCompiler’:
 class AMDGPUCompiler : public Compiler {
       ^
In file included from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:0:
/home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:194:28: note:  virtual amd::opencl_driver::BufferReference* amd::opencl_driver::Compiler::NewBufferReference(amd::opencl_driver::DataType, const char*, int, const string&)
   virtual BufferReference* NewBufferReference(DataType type, const char* ptr, size_t size, const std::string& id = "") = 0;
                            ^
compiler/driver/src/driver/CMakeFiles/opencl_driver.dir/build.make:62: recipe for target 'compiler/driver/src/driver/CMakeFiles/opencl_driver.dir/AmdCompiler.cpp.o' failed
make[2]: *** [compiler/driver/src/driver/CMakeFiles/opencl_driver.dir/AmdCompiler.cpp.o] Error 1
CMakeFiles/Makefile2:19547: recipe for target 'compiler/driver/src/driver/CMakeFiles/opencl_driver.dir/all' failed
make[1]: *** [compiler/driver/src/driver/CMakeFiles/opencl_driver.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fakenmc** [comment]
Hi, since there is no mention to cf4ocl code in the compilation log this issue does not seem related with cf4ocl. Could you please provide more information? In what context does this occur? When you try to compile cf4ocl? When you try to compile an OpenCL kernel with cf4ocl? Thanks

**Comment by dpratiher** [comment]
I am trying to build on ARM with kernel. Pls. find complete log.
ubuntu@ubuntu:~/amd/opencl/build$ uname -r
4.9.0+
------
ubuntu@ubuntu:~/amd/opencl/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial



ubuntu@ubuntu:~$ cd amd/opencl/build/
ubuntu@ubuntu:~/amd/opencl/build$ make
[ 75%] Built target LLVMDemangle
[ 75%] Built target LLVMSupport
[ 75%] Built target LLVMTableGen
[ 75%] Built target obj.llvm-tblgen
[ 75%] Built target llvm-tblgen
[ 75%] Updating AttributesCompatFunc.inc...
[ 75%] Built target AttributeCompatFuncTableGen
[ 75%] Updating Attributes.gen...
[ 75%] Updating Intrinsics.gen...
[ 75%] Built target intrinsics_gen
[ 75%] Built target LLVMCore
[ 75%] Built target LLVMIRReader
[ 75%] Built target LLVMCodeGen
[ 75%] Built target LLVMSelectionDAG
[ 75%] Built target LLVMAsmPrinter
[ 75%] Built target LLVMMIRParser
[ 75%] Built target LLVMGlobalISel
[ 75%] Built target LLVMBinaryFormat
[ 75%] Built target LLVMBitReader
[ 75%] Built target LLVMBitWriter
[ 75%] Built target LLVMTransformUtils
[ 75%] Built target LLVMInstrumentation
[ 75%] Built target LLVMInstCombine
[ 75%] Built target LLVMScalarOpts
[ 75%] Built target LLVMipo
[ 75%] Built target LLVMVectorize
[ 75%] Built target LLVMHello_exports
[ 75%] Built target LLVMHello
[ 75%] Built target LLVMObjCARCOpts
[ 75%] Built target LLVMCoroutines
[ 75%] Built target LLVMLinker
[ 75%] Built target LLVMAnalysis
[ 75%] Built target llvm_vcsrevision_h
[ 75%] Built target LLVMLTO
[ 75%] Built target LLVMMC
[ 75%] Built target LLVMMCParser
[ 75%] Built target LLVMMCDisassembler
[ 75%] Built target LLVMObject
[ 75%] Built target LLVMObjectYAML
[ 75%] Built target LLVMOption
[ 75%] Built target LLVMDebugInfoDWARF
[ 75%] Built target LLVMDebugInfoMSF
[ 75%] Built target LLVMDebugInfoCodeView
[ 75%] Built target LLVMDebugInfoPDB
[ 75%] Built target LLVMSymbolize
[ 75%] Built target LLVMExecutionEngine
[ 75%] Built target LLVMInterpreter
[ 75%] Built target LLVMMCJIT
[ 75%] Built target LLVMOrcJIT
[ 75%] Built target LLVMRuntimeDyld
[ 75%] Built target LLVMTarget
[ 75%] Updating AMDGPUGenRegisterInfo.inc...
[ 75%] Updating AMDGPUGenDAGISel.inc...
[ 75%] Updating AMDGPUGenCallingConv.inc...
[ 75%] Updating AMDGPUGenSubtargetInfo.inc...
[ 75%] Updating AMDGPUGenIntrinsics.inc...
[ 75%] Updating AMDGPUGenMCCodeEmitter.inc...
[ 75%] Updating AMDGPUGenDFAPacketizer.inc...
[ 75%] Updating AMDGPUGenAsmWriter.inc...
[ 75%] Updating AMDGPUGenAsmMatcher.inc...
[ 75%] Updating AMDGPUGenDisassemblerTables.inc...
[ 75%] Updating AMDGPUGenMCPseudoLowering.inc...
[ 75%] Built target AMDGPUCommonTableGen
[ 75%] Built target LLVMAMDGPUCodeGen
[ 75%] Built target LLVMAMDGPUUtils
[ 75%] Built target LLVMAMDGPUAsmParser
[ 75%] Built target LLVMAMDGPUAsmPrinter
[ 75%] Built target LLVMAMDGPUDisassembler
[ 75%] Built target LLVMAMDGPUInfo
[ 75%] Built target LLVMAMDGPUDesc
[ 75%] Built target LLVMAsmParser
[ 75%] Built target LLVMLineEditor
[ 75%] Built target LLVMProfileData
[ 75%] Built target LLVMCoverage
[ 75%] Built target LLVMFuzzerNoMainObjects
[ 75%] Built target LLVMFuzzerNoMain
[ 75%] Built target LLVMFuzzer
[ 75%] Built target LLVMPasses
[ 75%] Updating Options.inc...
[ 75%] Built target LibOptionsTableGen
[ 75%] Built target LLVMLibDriver
[ 75%] Built target LLVMXRay
[ 75%] Built target FileCheck
[ 75%] Built target llvm-PerfectShuffle
[ 75%] Built target count
[ 75%] Built target not
[ 75%] Built target yaml-bench
[ 75%] Built target gtest
[ 75%] Built target gtest_main
[ 75%] Built target LTO_exports
[ 75%] Built target LTO
[ 75%] Built target llvm-ar
[ 75%] Built target llvm-ranlib
[ 75%] Built target llvm-lib
[ 75%] Built target llvm-config
[ 75%] Built target llvm-lto
[ 75%] Built target llvm-profdata
[ 75%] Built target obj.clang-tblgen
[ 75%] Built target clang-tblgen
[ 75%] Updating arm_neon.h...
[ 75%] Built target clang-headers
[ 75%] Updating Checkers.inc...
[ 75%] Built target ClangSACheckers
[ 75%] Updating CommentCommandList.inc...
[ 75%] Built target ClangCommentCommandList
[ 75%] Updating CommentCommandInfo.inc...
[ 75%] Built target ClangCommentCommandInfo
[ 75%] Updating AttrVisitor.inc...
[ 75%] Built target ClangAttrVisitor
[ 75%] Updating CommentHTMLNamedCharacterReferences.inc...
[ 75%] Built target ClangCommentHTMLNamedCharacterReferences
[ 75%] Updating AttrDump.inc...
[ 75%] Built target ClangAttrDump
[ 75%] Updating AttrImpl.inc...
[ 75%] Built target ClangAttrImpl
[ 75%] Updating Attrs.inc...
[ 75%] Built target ClangAttrClasses
[ 75%] Updating StmtNodes.inc...
[ 75%] Built target ClangStmtNodes
[ 75%] Updating DeclNodes.inc...
[ 75%] Built target ClangDeclNodes
[ 75%] Updating CommentNodes.inc...
[ 75%] Built target ClangCommentNodes
[ 75%] Updating CommentHTMLTagsProperties.inc...
[ 75%] Built target ClangCommentHTMLTagsProperties
[ 75%] Updating CommentHTMLTags.inc...
[ 75%] Built target ClangCommentHTMLTags
[ 75%] Built target ClangDiagnosticIndexName
[ 75%] Built target ClangDiagnosticSerialization
[ 75%] Updating DiagnosticAnalysisKinds.inc...
[ 75%] Built target ClangDiagnosticAnalysis
[ 75%] Updating DiagnosticASTKinds.inc...
[ 75%] Built target ClangDiagnosticAST
[ 75%] Updating DiagnosticParseKinds.inc...
[ 75%] Built target ClangDiagnosticParse
[ 75%] Updating DiagnosticLexKinds.inc...
[ 75%] Built target ClangDiagnosticLex
[ 75%] Updating DiagnosticSemaKinds.inc...
[ 75%] Built target ClangDiagnosticSema
[ 75%] Updating DiagnosticCommentKinds.inc...
[ 75%] Built target ClangDiagnosticComment
[ 75%] Updating DiagnosticGroups.inc...
[ 75%] Built target ClangDiagnosticGroups
[ 75%] Updating DiagnosticDriverKinds.inc...
[ 75%] Built target ClangDiagnosticDriver
[ 75%] Updating AttrList.inc...
[ 75%] Built target ClangAttrList
[ 75%] Updating DiagnosticFrontendKinds.inc...
[ 75%] Built target ClangDiagnosticFrontend
[ 75%] Updating AttrHasAttributeImpl.inc...
[ 75%] Built target ClangAttrHasAttributeImpl
[ 75%] Updating DiagnosticCommonKinds.inc...
[ 75%] Built target ClangDiagnosticCommon
[ 75%] Updating AttrSubMatchRulesList.inc...
[ 75%] Built target ClangAttrSubjectMatchRuleList
[ 75%] Updating arm_neon.inc...
[ 75%] Built target ClangARMNeon
[ 75%] Updating AttrParserStringSwitches.inc...
[ 75%] Built target ClangAttrParserStringSwitches
[ 75%] Updating AttrSubMatchRulesParserStringSwitches.inc...
[ 75%] Built target ClangAttrSubMatchRulesParserStringSwitches
[ 75%] Updating AttrParsedAttrKinds.inc...
[ 75%] Built target ClangAttrParsedAttrKinds
[ 75%] Updating AttrSpellingListIndex.inc...
[ 75%] Built target ClangAttrSpellingListIndex
[ 75%] Updating AttrParsedAttrList.inc...
[ 75%] Built target ClangAttrParsedAttrList
[ 75%] Updating AttrParsedAttrImpl.inc...
[ 75%] Built target ClangAttrParsedAttrImpl
[ 75%] Updating AttrTemplateInstantiate.inc...
[ 75%] Built target ClangAttrTemplateInstantiate
[ 75%] Updating AttrPCHRead.inc...
[ 75%] Built target ClangAttrPCHRead
[ 75%] Updating AttrPCHWrite.inc...
[ 75%] Built target ClangAttrPCHWrite
[ 75%] Built target clangBasic
[ 75%] Built target clangLex
[ 75%] Built target clangParse
[ 75%] Built target clangAST
[ 75%] Built target clangASTMatchers
[ 75%] Built target clangDynamicASTMatchers
[ 75%] Built target clangSema
[ 75%] Built target clangCodeGen
[ 75%] Built target clangAnalysis
[ 75%] Built target clangEdit
[ 75%] Built target clangRewrite
[ 75%] Built target ClangDriverOptions
[ 75%] Built target clangDriver
[ 75%] Built target clangSerialization
[ 75%] Built target clangFrontend
[ 75%] Built target clangRewriteFrontend
[ 75%] Built target clangFrontendTool
[ 75%] Built target clangTooling
[ 75%] Built target clangToolingCore
[ 75%] Built target clangToolingRefactor
[ 75%] Built target clangIndex
[ 75%] Built target clangFormat
[ 75%] Built target diagtool
[ 75%] Built target clang-offload-bundler
[ 75%] Built target clang
[ 75%] Built target clang-format
[ 75%] Built target clang-import-test
[ 75%] Built target libclang_exports
[ 75%] Built target libclang
[ 75%] Built target c-index-test
[ 75%] Built target lldConfig
[ 75%] Built target lldCore
[ 75%] Updating DarwinLdOptions.inc...
[ 75%] Built target DriverOptionsTableGen
[ 75%] Built target lldDriver
[ 75%] Built target lldReaderWriter
[ 75%] Built target lldMachO
[ 75%] Built target lldYAML
[ 75%] Updating Options.inc...
[ 75%] Built target ELFOptionsTableGen
[ 75%] Built target lldELF
[ 75%] Updating Options.inc...
[ 75%] Built target COFFOptionsTableGen
[ 75%] Built target lldCOFF
[ 75%] Built target lld
[ 75%] Updating Opts.inc...
[ 75%] Built target CvtResTableGen
[ 75%] Built target llvm-cvtres
[ 75%] Built target llvm-dwp
[ 75%] Built target llvm-nm
[ 75%] Built target llvm-diff
[ 75%] Built target llvm-cxxfilt
[ 75%] Built target llvm-cat
[ 75%] Built target llvm-cov
[ 75%] Built target lli
[ 75%] Built target lli-child-target
[ 75%] Built target llvm-as
[ 75%] Built target obj2yaml
[ 75%] Built target llvm-stress
[ 75%] Built target sanstats
[ 75%] Built target sancov
[ 75%] Built target llvm-symbolizer
[ 75%] Built target bugpoint
[ 75%] Built target llvm-dis
[ 75%] Built target llvm-objdump
[ 75%] Built target llvm-strings
[ 75%] Built target llvm-link
[ 75%] Built target llvm-split
[ 75%] Built target llvm-pdbdump
[ 75%] Built target llvm-mcmarkup
[ 75%] Built target llvm-opt-report
[ 75%] Built target verify-uselistorder
[ 75%] Built target llvm-cxxdump
[ 75%] Built target llvm-lto2
[ 75%] Built target llvm-readobj
[ 75%] Built target llvm-modextract
[ 75%] Built target llvm-extract
[ 75%] Built target llvm-rtdyld
[ 75%] Built target llvm-dwarfdump
[ 75%] Built target llc
[ 75%] Built target opt
[ 75%] Built target yaml2obj
[ 75%] Built target llvm-dsymutil
[ 75%] Built target amdgpu-objdump
[ 75%] Built target llvm-bcanalyzer
[ 75%] Built target llvm-size
[ 75%] Built target llvm-mc
[ 75%] Built target llvm-xray
[ 75%] Built target BugpointPasses_exports
[ 75%] Built target BugpointPasses
[ 75%] Built target llvm-c-test
[ 75%] Building CXX object compiler/driver/src/driver/CMakeFiles/opencl_driver.dir/AmdCompiler.cpp.o
In file included from /usr/include/wchar.h:51:0,
                 from /usr/include/c++/5/cwchar:44,
                 from /usr/include/c++/5/bits/postypes.h:40,
                 from /usr/include/c++/5/bits/char_traits.h:40,
                 from /usr/include/c++/5/string:40,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:128:39: error: missing binary operator before token "("
 #if !defined(_WINT_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/sched.h:28:0,
                 from /usr/include/pthread.h:23,
                 from /usr/include/aarch64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/aarch64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/basic_string.h:39,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/time.h:37:0,
                 from /usr/include/pthread.h:24,
                 from /usr/include/aarch64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/aarch64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/basic_string.h:39,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/stdlib.h:32:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/aarch64-linux-gnu/sys/types.h:146:0,
                 from /usr/include/stdlib.h:314,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/alloca.h:24:0,
                 from /usr/include/stdlib.h:492,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/stdio.h:33:0,
                 from /usr/include/c++/5/cstdio:42,
                 from /usr/include/c++/5/ext/string_conversions.h:43,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/_G_config.h:15:0,
                 from /usr/include/libio.h:31,
                 from /usr/include/stdio.h:74,
                 from /usr/include/c++/5/cstdio:42,
                 from /usr/include/c++/5/ext/string_conversions.h:43,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/home/ubuntu/amd/opencl/compiler/llvm/tools/clang/lib/Headers/stddef.h:57:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
In file included from /usr/include/c++/5/cwchar:44:0,
                 from /usr/include/c++/5/bits/postypes.h:40,
                 from /usr/include/c++/5/bits/char_traits.h:40,
                 from /usr/include/c++/5/string:40,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.h:4,
                 from /home/ubuntu/amd/opencl/compiler/driver/src/driver/AmdCompiler.cpp:1:
/usr/include/wchar.h:153:38: error: ‘size_t’ has not been declared
     const wchar_t *__restrict __src, size_t __n)
                                      ^
/usr/include/wchar.h:162:38: error: ‘size_t’ has not been declared
     const wchar_t *__restrict __src, size_t __n)
                                      ^
/usr/include/wchar.h:169:63: error: ‘size_t’ has not been declared
 extern int wcsncmp (const wchar_t *__s1, const wchar_t *__s2, size_t __n)
                                                               ^
/usr/include/wchar.h:179:4: error: ‘size_t’ has not been declared
    size_t __n) __THROW;

**Comment by fakenmc** [comment]
It appears you are trying to build **AMD's OpenCL** implementation. This is **cf4ocl**'s repository, which is not related with **AMD's OpenCL**. As such, this is not the place to seek help for your problem. Closing the issue.
